title: MailboxJunkEmailConfiguration  Manipulation From Suspicious Country
id: 1b3d5587-4e96-4a4d-be85-2617620c3383
status: experimental
description: Detects change to MailboxJunkEmailConfiguration from an IP in a suspicious country.
references: https://redcanary.com/threat-detection-report/techniques/email-forwarding-rule/
tags: 
  - attack.collection
  - attack.t1114.003
author: Inovasys
date: 2024/03/27
level: medium 
Language: KQL
Prerequisites: CloudAppEvents
Query: |
'let countries = dynamic(["US","AT"]); //Add countries that you operate in
CloudAppEvents
| where Application == "Microsoft Exchange Online"
| where ActionType == "Set-MailboxJunkEmailConfiguration"
| where not(CountryCode in (countries))'