attack_technique: T1204.002
display_name: "User Execution: Malicious File"
atomic_tests:
- name: Word Spawning Suspicious Child
  auto_generated_guid: 3898048d-9c43-4466-8294-6a5fb9e84b6a
  description: |
    Launches a macro enabled word document that starts an instance of rundll32.exe
  supported_platforms:
  - windows
  input_arguments:
    macro_file:
      description: Path to macro enabled word document
      type: path
      default: PathToAtomicsFolder\rundll32_suspicious_parent\bin\rundll32spawn.docm
  dependency_executor_name: powershell
  dependencies:
    - description: Test if document exists
      prereq_command: |
        if(Test-Path "#{macro_file}") {exit 0} else {exit 1}
      get_prereq_command: |
        Invoke-WebRequest "https://github.com/Inovasys-CS/EDI/raw/main/execution/Office_application_spawning_another_process/bin/rundll32spawn.docm" -OutFile "#{dll_file}"
  executor:
    command: |
      start #{macro_file}
    cleanup_command: |
      Remove-Item -Path #{macro_file}
    name: powershell